on: [push]

jobs:
  First-Job:
    runs-on: ubuntu-latest
    name: A Job to execute an action in another repo (frameworkRepo)
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: rogeruiz22/frameworkRepo@v6
        with:
          who-to-greet: "Incubator Team !"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
